#!/bin/dash

if test ! -e ".girt"
then
	echo "girt-rm: error: girt repository directory .girt not found"
	exit 1
fi

if test $# -lt 2
then
	echo "usage: girt-rm [--force] [--cached] <filenames>"
	exit 1
fi

cach="$1"
#fileToRemove="$2"

#if --cached
if [ "$1" = "--cached" ]
then
	for file in $(ls .girt/.index)
	do
		if test  ! -e ".girt/.index"/"$file"
		then
			echo "girt-rm: error: '$file' is not in the girt repository"
			exit 1
		else
			rm ".girt/.index/$file"
			exit 0
		fi
	done
fi
			
