#!/bin/dash

#set -u

if [ ! -d .girt ]
then
	echo "girt-show: error: no .girt directory containing girt repository exists" 1&>2
	exit 1
fi

commit=$(echo "$1" | cut -d ':' -f1)
filename=$(echo "$1" | cut -d ':' -f2)

# test is num commits exists
if test ! -d .girt/.commit/"$commit"
then
	echo "girt-show: error: unknown commit '$commit'"
	exit 1
fi

# test if commit is numeric if not throw error
if test "$commit" | egrep '^[^0-9]'
then
	echo "girt-show: error: unknown commit '$commit'"
	exit 1
fi

# test is filename is empty
if test -z "$filename"
then
	echo "girt-show: error: invalid filename '$filename'"
	exit 1
fi


#if commit num is empty check index
if [ -z "$commit" ]
then
	# look for file in commit
	#if test -e .girt/.commit/"$filename"
	#then
	#	cat .girt/.commit/"$filename"
	#	exit 0
	#fi
	if [ ! -f .girt/.index/"$filename" ]
	then
		#check to see if file exists in commit 
		if test -f .girt/.commit/"$filename"
		then
			cat .girt/.commit/"$filename"
			exit 0
			
		else
			echo "girt-show: error: '$filename' not found in index"
			exit 1
		fi
		echo "girt-show: error: '$filename' not found in index"
		exit 1
	fi
	cat .girt/.index/"$filename"
	exit 0
fi

# test is file exists in specific commit
if test ! -f .girt/.commit/"$commit"/"$filename"
then
	echo "girt-show: error: '$filename' not found in commit $commit"
	exit 1
fi

cat .girt/.commit/"$commit"/"$filename"
