#!/bin/dash

if test -e .girt
then
	echo "girt-init: error: .girt already exists"
else
	mkdir .girt
	echo "Initialized empty girt repository in .girt"


	cd .girt
	mkdir .index
	mkdir .commit
	touch log.txt
	cd ..
fi

